{% set name = "shapelysmooth" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shapelysmooth-{{ version }}.tar.gz
  sha256: 34a2a460fe7907e0eea16c24abcd8885dba29e89e903164e23c807e6250d549b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pybind11
    - pip
  run:
    - python
    - libgcc-ng  # [linux]
    - libstdcxx-ng  # [linux]
    - shapely

test:
  imports:
    - shapelysmooth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/philipschall/shapelysmooth
  summary: A polyline smoothing package for shapely.
  license: Unlicense
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - raybellwaves
