# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.2.1

package:
  name: shapelysmooth
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/shapelysmooth/shapelysmooth-${{ version }}.tar.gz
  sha256: 34a2a460fe7907e0eea16c24abcd8885dba29e89e903164e23c807e6250d549b

build:
  number: 2
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - pybind11
        - python
  host:
    - pip
    - pybind11
    - python
    - setuptools
  run:
    - python
    - shapely

tests:
  - python:
      pip_check: true
      imports: shapelysmooth
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest-cov
    script:
      - coverage run --source shapelysmooth --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=96

about:
  summary: A polyline smoothing package for shapely.
  license: Unlicense
  license_file: LICENSE.txt
  homepage: https://github.com/philipschall/shapelysmooth

extra:
  recipe-maintainers:
    - raybellwaves
    - bollwyvl
